theme: jekyll-theme-architect
title: **The Blogger's code of ethics**

#What are the code of ethics?#
Description:The blogger's code of ethics was written by Tim O’Reilly and Jimmy Wales in response to controversy surrounding blogger Kathy Sierra revieivng death threats.
-Take responsibility not just for your own words, but for the comments you allow on your blog.
-Label your tolerance level for abusive comments.
-Consider eliminating anonymous comments.
-Don't feed the trolls.
-If you know someone who is behaving badly, tell them so.
-Don't say anything online that you wouldn't say in person.
